name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Tools
      run: |
        pip install bandit
        sudo apt-get update
        sudo apt-get install docker.io -y
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

    - name: Run Bandit
      run: bandit -r .

    - name: Build Docker Image
      run: docker build -t devsecops-app .

    - name: Run Trivy Scan (FAIL on HIGH/CRITICAL)
      run: ./trivy image --exit-code 1 --severity HIGH,CRITICAL devsecops-app